apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-student-5
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: student-5
  project: default
  source:
    repoURL: https://github.com/haghdk/argocd/
    targetRevision: HEAD
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true